name: Test-echo
on:
  issues:
    types: [closed]
  pull_request:
    types: [opened]
jobs:
  test-echo:
    runs-on: ubuntu-latest
    env:
      t: ${{ secrets.T1 }}
    steps:
      - name: Test0
        run: echo "$t"
      - name: Test1
        run: echo ${t:0:3}
